---
- name: set timezone
  timezone:
    name: "{{ system_timezone }}"

- name: ensure locale files are present
  locale_gen:
    name: "{{ system_lang }}"
    state: present

- name: get current locale configuration
  command: localectl status
  register: locale_status
  changed_when: false

- name: parse 'LANG' from current locale configuration
  set_fact:
    locale_lang: "{{ locale_status.stdout \
                 | regex_search('LANG=([^\n]+)', '\\1') \
                 | default([''], true) \
                 | first }}"

- name: configure locale
  command: localectl set-locale LANG={{ system_lang }}
  changed_when: locale_lang != system_lang
